### PR TITLE
Update LP_snapshot_address.txt

### PR DESCRIPTION
**Pull request by Rudra221**

### CODE REVIEW

**Comment by BitcoinEtherium** [comment]
0x47d7fc3bc8c753f5857f908935a44e51956d70efce9e4142eae3c0c4d6732349

**Comment by gusmantoro77** [comment]
0xf6d923978ea3887c9ce45fe1490ba55e7747ed8852b5ddaffbd676316ca8ee4f

**Comment by leejua486** [comment]
0x54b2584b96532e92df0e6752a77ae268d6a73a785874d593faacb0e64b40c4be

**Comment by leejua486** [comment]
image


:)

**Comment by BitcoinEtherium** [comment]
Salut tu peut m expliquer

Envoyé depuis Proton Mail mobile

-------- Message d'origine --------

**Comment by Sergiomajori** [comment]
0x40cb16802a8c517066bc0a6e9e73e00b0140c57d3d73d6b830d1c12cd52a5e07

**Comment by Sergiomajori** [comment]
0x40cb16802a8c517066bc0a6e9e73e00b0140c57d3d73d6b830d1c12cd52a5e07

**Comment by BitcoinEtherium** [comment]
Salut

**Pull request closed without merging**
