### PR TITLE
Update OG_bind_address.txt

### PR DESCRIPTION
**Pull request by yasar-ustaaa**

### CODE REVIEW

**Comment by shahinfestival** [comment]
Hi

**Comment by dodot15** [comment]
0xcec0e636490a8794c26ac0c5a0cab27303618e9848e737043eb3325445c76b35

**Comment by Yoshirangers** [comment]
0x4ee0607e45851a0b43fc27ce2414db8b40df1f3c630a5fac14d886bdcdd24085

**Comment by quocdaikk** [comment]
Yes sir

Vào Th 6, 11 thg 11, 2022 lúc 17:36 Yoshirangers ***@***.***>
đã viết:

**Review by Gurpreet5845 — COMMENTED** [review]
0x97ff0fa2b91363a08b945a60f8a6826a3112be12720ec1ceb23165cac434e5af

**Comment by Gurpreet5845** [comment]
0x97ff0fa2b91363a08b945a60f8a6826a3112be12720ec1ceb23165cac434e5af

**Comment by shahinfestival** [comment]
Tnx for this massage

**Comment by quocdaikk** [comment]
I joined but not on the list, please add me
my apt wallet;
0x68ba1b962e41b29a01b7519578b8cf35ed2db918292e16375f8e19dd1d8c2c78

Vào CN, 13 thg 11, 2022 vào lúc 18:48 Azard ***@***.***> đã
viết:

**Comment by shahinfestival** [comment]
I joined but not on the list, please add me
my apt wallet; 
0x4ec8569bf24923f391e247051f6febda6ceed7267e0a589415c7b22f87de8386

**Comment by sansanwijaya** [comment]
0x0D6B89E3A265130EC3f6Aa6fB5f0ACc2c3869428

Pada tanggal Jum, 11 Nov 2022 17.36, Yoshirangers ***@***.***>
menulis:

**Comment by quocdaikk** [comment]
Yes sir

Vào Th 2, 14 thg 11, 2022 lúc 06:25 sansanwijaya ***@***.***>
đã viết:

**Comment by octavianfilippov** [comment]
I have joined, please add my wallet on the list.
0xa72d9bc8536a49cc3e44d39ca2be8fdb371265f2a520caf1ca808c0ff532fc3a

**Comment by quocdaikk** [comment]
Done.

Vào Th 2, 14 thg 11, 2022 lúc 20:33 octavianfilippov <
***@***.***> đã viết:

**Pull request closed without merging**
